---
variables:
  AUDIT_AWS_INVENTORY_ALERT_RECIPIENT:
    description: Enter the email address(es) that will receive notifications. If more
      than one, separate each with a comma.
    required: false
    type: string
  AUDIT_AWS_INVENTORY_ALLOW_EMPTY:
    description: Would you like to receive empty reports? Options - true / false.
      Default is false.
    required: true
    type: string
    default: false
  AUDIT_AWS_INVENTORY_SEND_ON:
    description: Send reports always or only when there is a change? Options - always
      / change. Default is change.
    required: true
    type: string
    default: change
  AUDIT_AWS_INVENTORY_OWNER_TAG:
    description: Enter an AWS tag whose value is an email address of the owner of
      the AWS services being audited. (Optional)
    required: true
    type: string
    default: NOT_A_TAG
  AUDIT_AWS_INVENTORY_REGIONS:
    description: List of AWS regions to check. Default is all regions. Choices are
      ap-northeast-1,ap-northeast-2,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-west-1,eu-west-2,sa-east-1,us-east-1,us-east-2,us-west-1,us-west-2
    required: true
    type: array
    default:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  AUDIT_AWS_#{service.upcase}_ALERT_LIST:
    description: Which rules would you like to run? Possible values are acm-inventory-certificates
    required: false
    type: array
    default:
    - acm-inventory-certificates
